apiVersion: v1
kind: Pod
metadata:
  labels:
    run: giropops
  name: giropops
spec:
  containers:
  - image: nginx
    name: webserver
    volumeMounts:
      - mountPath: /giropops
        name: volume-emptydir
    args:
      - sleep  
      - "1800"
    resources:
      limits:
        cpu: "1"
        memory: "128Mi"
      requests:
        cpu: "0.5"
        memory: "64Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: volume-emptydir
      emptyDir: 
        sizeLimit:  "256Mi"
status: {}