apiVersion: v1
kind: Pod
metadata:
  labels:
    run: task-pod
  name: task-pod
spec:
  containers:
  - image: ubuntu
    name: ubuntu
    volumeMounts:
    - mountPath: /tmp-ubuntu
      name: ubuntu-volume
    args:
      - sleep  
      - "1800"
    resources:
      limits:
        cpu: "0.5"
        memory: "128Mi"
      requests:
        cpu: "0.3"
        memory: "64Mi"
  - image: nginx
    name: nginx
    args:
      - sleep  
      - "1800"
    volumeMounts:
    - mountPath: /tmp-nginx
      name: nginx-volume
    resources:
      limits:
        cpu: "0.8"
        memory: "256Mi"
      requests:
        cpu: "0.5"
        memory: "128Mi"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
  - name: ubuntu-volume
    emptyDir: {}
  - name: nginx-volume
    emptyDir: {}
status: {}